//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorien.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lorien.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;iata&quot;: &quot;UTK&quot;,
        ///        &quot;lon&quot;: &quot;169.86667&quot;,
        ///        &quot;iso&quot;: &quot;MH&quot;,
        ///        &quot;status&quot;: 1,
        ///        &quot;name&quot;: &quot;Utirik Airport&quot;,
        ///        &quot;continent&quot;: &quot;OC&quot;,
        ///        &quot;type&quot;: &quot;airport&quot;,
        ///        &quot;lat&quot;: &quot;11.233333&quot;,
        ///        &quot;size&quot;: &quot;small&quot;
        ///    },
        ///    {
        ///        &quot;iata&quot;: &quot;FIV&quot;,
        ///        &quot;iso&quot;: &quot;US&quot;,
        ///        &quot;status&quot;: 1,
        ///        &quot;name&quot;: &quot;Five Finger CG Heliport&quot;,
        ///        &quot;continent&quot;: &quot;NA&quot;,
        ///        &quot;type&quot;: &quot;heliport&quot;,
        ///        &quot;size&quot;: null
        ///    },
        ///    {
        ///        &quot;iata&quot;: &quot;FAK&quot;,
        ///        &quot;iso&quot;: &quot;US&quot;,
        ///        &quot;status&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string airports {
            get {
                return ResourceManager.GetString("airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;entity&quot;: &quot;DOMINICA&quot;, &quot;currency&quot;: &quot;East Caribbean Dollar&quot;, &quot;alphabeticcode&quot;: &quot;XCD&quot;, &quot;numericcode&quot;: &quot;951&quot;, &quot;minorunit&quot;: &quot;2&quot;, &quot;withdrawaldate&quot;: null},{&quot;entity&quot;: &quot;MALDIVES&quot;, &quot;currency&quot;: &quot;Rufiyaa&quot;, &quot;alphabeticcode&quot;: &quot;MVR&quot;, &quot;numericcode&quot;: &quot;462&quot;, &quot;minorunit&quot;: &quot;2&quot;, &quot;withdrawaldate&quot;: null},{&quot;entity&quot;: &quot;NEW ZEALAND&quot;, &quot;currency&quot;: &quot;New Zealand Dollar&quot;, &quot;alphabeticcode&quot;: &quot;NZD&quot;, &quot;numericcode&quot;: &quot;554&quot;, &quot;minorunit&quot;: &quot;2&quot;, &quot;withdrawaldate&quot;: null},{&quot;entity&quot;: &quot;PAPUA NEW GUINEA&quot;, &quot;currency&quot;: &quot;Kina&quot;, &quot;alphabeticcode&quot;: &quot;PGK&quot;, &quot;n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string currency_codes {
            get {
                return ResourceManager.GetString("currency-codes", resourceCulture);
            }
        }
    }
}
